### ISSUE TITLE
Ansible

### ISSUE THREAD

**Issue by GeeCastro** [briancappello/flask-react-spa#11]
Hi, I am having an issue running ansible playbook in both dev and deploy envs
dev env
```
TASK [flask : create virtualenv /virtualenvs/flask_api] ************************
fatal: [centos74.io]: FAILED! => {"changed": false, "cmd": "virtualenv -p /usr/bin/python3.6 /virtualenvs/flask_api", "msg": "[Errno 2] No such file or directory", "rc": 2}
```
deploy env
```
TASK [flask : create virtualenv /virtualenvs/flask_api] ************************************************************************************************************
fatal: [centos74.io]: FAILED! => {"changed": false, "cmd": "virtualenv -p /usr/bin/python3.6 /virtualenvs/flask_api", "msg": "[Errno 2] No such file or directory", "rc": 2}

```
I found it is called on file `flask-react-spa/ansible/roles/flask/tasks/install_virtualenv.yaml`. So I tried editing without success. I assume it is considering /virtualenvs/flask_api as a path and it doesn't exist ?

cheers.
G.

Running this on ubuntu 18.04, using vm as presented in ansible/dev-scripts.

**Comment by briancappello** [comment]
Hey, thanks for the report! The ansible scripts were developed on Ansible 2.2 if I recall correctly, and I believe they sould work with 2.4. But yes, I ran into similar problems using 2.8. It seems like Ansible is somehow getting confused about which version of Python to use. I did try mucking around with it a bit, but I wasn't able to figure it out. Decided to punt with CentOS 8.0 just released (which includes 3.6 out of the box) - but I haven't gotten around to upgrading things just yet :/

**Comment by GeeCastro** [comment]
Thanks for your answer (sorry for the delay). 
After learning more about ansible, there is an easy (dirty) fix. 

- Copy (to remote host) a dummy reqs.txt file placed under `ansible/playbooks/` folder.
- Create an virtualenv as proposed in the [ansible 2.8 docs](https://docs.ansible.com/ansible/2.8/modules/pip_module.html) every time a new virtualenv is needed.

```
- name: Copy reqs.txt file with owner and permission
  copy:
    src: reqs.txt ## ansible will find it under ansible/playbook/ or ansible/playbook/files/
    dest: /
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: create virtualenv {{ project_virtualenv_dir }} 
  pip: 
    requirements: /reqs.txt
    virtualenv: "{{ project_virtualenv_dir }}"
    virtualenv_python: "{{ python3_path }}"
    virtualenv_command: /usr/local/bin/virtualenv ## make sure ansible picks up the correct executable
```
I hope this helps. I was able to have it running in dev. (couldn't test the prod because of lets encrypt)
